complete/CRUD/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

complete/core/urls.py
from django.urls import path
from . import views
from . views import *

app_name = 'core'

urlpatterns = [
    path('', views.employee_form, name='employee_insert'),
    path('<int:id>/', views.employee_form, name='employee_update'),
    path('list/', views.employee_list, name='employee_list'),
    path('delete/<int:id>/', views.employee_delete, name='employee_delete'),
    path('home_page', views.home_page, name = 'home_page')
]

complete/core/models.py
from django.db import models


class position(models.Model):
    title  = models.CharField(max_length=50)
    
    def __str__(self):
        return self.title

class Employee(models.Model):
    fullname = models.CharField(max_length=30)
    emp_code = models.CharField(max_length=4)
    mobile = models.CharField(max_length=30)
    position = models.ForeignKey(position, on_delete=models.CASCADE)

    def __str__(self):
        return self.fullname

complete/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class CoreEmployee(models.Model):
    id = models.BigAutoField(primary_key=True)
    fullname = models.CharField(max_length=30)
    emp_code = models.CharField(max_length=4)
    mobile = models.CharField(max_length=30)
    position = models.ForeignKey('CorePosition', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'core_employee'


class CorePosition(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'core_position'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

complete/core/forms.py
from django import forms
from . models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

        labels = {
            'fullname':'Full Name',
            'emp_code': 'EMP-Code'
        }

    def __init__(self, *args, **kwargs):
        super(EmployeeForm,self).__init__(*args, **kwargs)
        self.fields['position'].empty_label = "Select"
        self.fields['emp_code'].required = False
        self.fields['fullname'].required = False
        self.fields['position'].required = False
        self.fields['mobile'].required = False

complete/core/views.py
from django.shortcuts import render, redirect
from . models import Employee
from . forms import EmployeeForm

# def home(request):
    # return render(request, "base.html")

def employee_list(request):
    context = {'employee_list':Employee.objects.all()}
    return render(request, "employee_list.html", context)

def employee_form(request, id=0):
    if request.method == "GET":
        if id == 0:
            form = EmployeeForm()
        else:
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(instance=employee)
            
        context = {"form":form}
        return render(request, "employee_form.html", context)
    else:
        if id == 0:
            form = EmployeeForm(request.POST)
        else:
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(request.POST,instance=employee)
        if form.is_valid():
            form.save()
        return redirect('/list/')    

def employee_delete(request, id):
    employee = Employee.objects.get(pk=id)
    employee.delete()
    return redirect('/list/')

def home_page(request):
    return render(request, 'home_page.html')
    

complete/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" integrity="sha384-ejwKkLla8gPP8t2u0eQyL0Q/4ItcnyveF505U0NIobD/SMsNyXrLti6CWaD0L52l" crossorigin="anonymous">">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    </head>
<style>
    .bd{
        background-image: url({% static "images/background.jpg" %});
        background-size:cover;
    }
    .container{
        /* display: flex; */
        background-color:orange;
        border-style: none;
        width: 700px;
        margin-top: 30px;
        /* margin: auto; */
        height: auto;
        justify-content: center;
        align-self: center;  
        /* margin-top: 100px;        */
    }
    .display-4{
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        color: blueviolet;
    }
    .lead{
        font-style: italic;
    }
    .block-content{
        font-style: italic;
    }
</style>
<body class="bd">
    <div class="container">
        <div class="col-md-10 offset-md-1 mt-5" >
            <div class="jumbotron">
                <h1 class="display-4">Employees Register</h1>
                <p class="lead">Python Django Project for implementing crud operations.</p>
                <hr class="my-4">
                    <div class="block-content">
                        {% block content %}
                        {% endblock content %}
                    </div>
                    <br>
                <a href="{% url 'core:home_page' %}"  class="btn btn-primary ">Learn More</a>
                        <!-- <a href="{% url 'core:home_page' %}" class="btn btn-primary" ></a> -->
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

complete/core/templates/employee_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST" action="" autocomplete="off">
    {% csrf_token %}
    {{form.fullname|as_crispy_field}}
    {{form.mobile|as_crispy_field}}
    <div class="row">
        <div class="col-md-4">
            {{form.emp_code|as_crispy_field}}
        </div>
        <div class="col-md-8">
            {{form.position|as_crispy_field}}
        </div>
    </div><br>
    <div class="row">
        <div class="col-md-8">
            <button href="" type="submit" class="btn btn-success btn-block btn-lg">Submit</button> 
            </div>            
            <div class="col-md-4">
                <a href="{% url 'core:employee_list' %}" class="btn btn-secondary btn-block btn-lg" >Back to list</a>

    </div>
</div>
</form>
{% endblock content %}

complete/core/templates/employee_list.html
{% extends "base.html" %}
{% load static %}
{%block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<table class="table table-hover">
    <!-- <thead> -->
        <tr style="font-weight: bold;font-family: Verdana, Geneva, Tahoma, sans-serif;">
            <td>Full Name</td>
            <td>Mobile</td>
            <td>Position</td>
            <td> </td>
            <td>
                <a href="{% url 'core:employee_insert' %}" class="btn btn-success">
                        <i class="fas fa-plus"></i>Add New
                </a>
            </td>
            <td></td>
        </tr>
    <!-- </thead> -->
    <tbody>
        {% for employee in employee_list %}
        <tr>
            <td>{{employee.fullname}}</td>
            <td>{{employee.mobile}}</td>
            <td>{{employee.position}}</td>
            <td>    
             
           <a   href="{% url 'core:employee_update' employee.id %}" class="btn btn-primary">Update
               <!-- <button type="submit" class="btn btn-primary"> -->
                   <!-- <a href="{% url 'core:employee_update' employee.id%}"></a> -->
                   <!-- Update</button> -->
              </a>
            </td>
            <td><form action="{% url 'core:employee_delete' employee.id %}" method="POST" class="d-inline" >
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Delete
                </button>
            </form></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

complete/core/templates/home_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<style>
    .pic{
        border: none;
        height: 250px;
        width: 350px;
    }
</style>
<body style="background-color: darkgray;">
    <h1>Hello world!!!!</h1>
    <i class="bi-alarm"></i>
    <p><h2>Welcome to Django.</h2></p>
    <br>
    <div class="row">
        <div class="col-md-4">
    <img class="pic" src="{% static 'images/background.jpg'%}" alt="Image">
    </div>
    </div>
</body>
</html>